"""add_description_to_loans

Revision ID: 15c9b90dbd9d
Revises: 97ccae5e8d23
Create Date: 2025-12-21 21:29:09.249326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c9b90dbd9d'
down_revision: Union[str, None] = '97ccae5e8d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'description')
    # ### end Alembic commands ###
