"""Add missing column

Revision ID: 7f7e38e94fbc
Revises: d8e3f6a2b3c4
Create Date: 2025-12-02 18:56:08.556090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7e38e94fbc'
down_revision: Union[str, None] = 'd8e3f6a2b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('system_settings_key_key', 'system_settings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('system_settings_key_key', 'system_settings', ['key'])
    # ### end Alembic commands ###
